# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('GUID', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('nationality', models.CharField(max_length=128)),
                ('NLanguge', models.CharField(max_length=128)),
                ('NLanguge2', models.CharField(max_length=128)),
                ('LLanguge', models.CharField(max_length=128)),
                ('LLanguge2', models.CharField(max_length=128)),
            ],
        ),
    ]
