# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LanguageExchange', '0002_auto_20170316_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='picture',
            field=models.ImageField(blank=True, upload_to=b'profile_images'),
        ),
    ]
